### ISSUE TITLE
whats client dragonnest.exe version?

### ISSUE THREAD

**Issue by distroitcdn** [alin1337/DNSkyProject#1]
hello,
compile success no problem, but error for make executable client, dragonnest.exe size 5MB can't attach dll
using dnsky resource problem again, can't play and get serverlist but not critical IP stack i change on dconnect.cpp
i implement on change EXT DNT, but problem Client Version Mismatch

**Comment by alin1337** [comment]
Version 1.1651.0 TW

**Comment by distroitcdn** [comment]
thanks!
